apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-certs
  namespace: coder # Coder deployment namespace
spec:
  commonName: "*.swo-aks.demo.coder.com"
  dnsNames:
  - "swo-aks.demo.coder.com"
  - "*.swo-aks.demo.coder.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: coder-certs
